"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Clock, Mail } from "lucide-react";
import { fetchNewsletters, type Newsletter } from "@/lib/newsletters";

export default function NewsletterPage() {
  const [items, setItems] = useState<Newsletter[]>([]);
  const [selected, setSelected] = useState<Newsletter | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetchNewsletters().then((data) => { setItems(data); const slug = new URLSearchParams(window.location.search).get("issue"); setSelected(data.find((item) => item.slug === slug) ?? null); }).finally(() => setLoading(false)); }, []);
  if (selected) return <main className="min-h-screen bg-[#faf9f7] pb-24 pt-[70px]"><header className="bg-[#263f57] px-4 py-16 text-white lg:py-24"><div className="mx-auto max-w-[900px]"><button onClick={() => { setSelected(null); history.replaceState(null, "", "/newsletter/"); }} className="mb-10 inline-flex items-center gap-2 text-sm font-semibold text-white/60 hover:text-white"><ArrowLeft size={16} /> All issues</button><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#efb2a8]">{selected.series} · {selected.issue}</p><h1 className="mt-6 text-[clamp(2.35rem,5vw,4.7rem)] font-bold leading-[1.03] tracking-[-0.04em]">{selected.title}</h1><p className="mt-7 max-w-2xl text-lg leading-7 text-white/70">{selected.excerpt}</p></div></header><article className="mx-auto max-w-[760px] px-4 pt-14 sm:px-6 lg:pt-20">{selected.sections.map((section, index) => section.type === "quote" ? <blockquote key={index} className="my-12 rounded-[24px] border-l-4 border-[#c87568] bg-[#263f57] p-8 text-2xl font-bold leading-snug text-white">{section.paragraphs[0]}</blockquote> : <section key={index} className="mb-11">{section.heading && <h2 className="mb-5 text-3xl font-bold leading-tight text-[#263f57]">{section.heading}</h2>}<div className={section.type === "lead" ? "text-lg font-medium leading-8 text-[#485b67]" : "text-base leading-8 text-[#55646d]"}>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mb-5">{paragraph}</p>)}</div></section>)}{selected.researchNote && <aside className="mt-14 rounded-2xl bg-[#edf3f1] p-6 text-sm leading-6 text-[#526b65]"><strong className="mb-2 block text-[#263f57]">Research note</strong>{selected.researchNote}</aside>}</article></main>;
  return <main className="min-h-screen bg-[#f7f5f1] pb-20 pt-[70px]"><section className="bg-[#263f57] py-20 text-white"><div className="mx-auto max-w-[1180px] px-4 sm:px-6"><div className="mb-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#efb2a8]"><Mail size={14} /> WholeLife Insights</div><h1 className="max-w-4xl text-[clamp(2.5rem,5vw,4.8rem)] font-bold leading-none">Ideas for the decisions that shape a lifetime.</h1></div></section><section className="mx-auto max-w-[1180px] px-4 py-14 sm:px-6"><h2 className="mb-8 text-3xl font-bold text-[#263f57]">All issues</h2>{loading ? <p>Loading newsletters…</p> : <div className="grid gap-5 md:grid-cols-2">{items.map((item) => <button key={item.slug} onClick={() => { setSelected(item); history.replaceState(null, "", `/newsletter/?issue=${item.slug}`); scrollTo(0, 0); }} className="group rounded-[24px] border border-[#263f57]/10 bg-white p-8 text-left shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#c87568]">{item.issue}</p><h2 className="mt-5 text-2xl font-bold leading-tight text-[#263f57]">{item.title}</h2><p className="mt-4 text-sm leading-6 text-[#6d777c]">{item.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#263f57]">Read issue <ArrowRight size={15} /></span></button>)}</div>}{!loading && !items.length && <div className="text-center text-[#7a8388]"><BookOpen className="mx-auto mb-3" />No issues published yet.</div>}<div className="mt-6 text-xs text-[#7a8388]"><Clock size={12} className="mr-1 inline" />New issues appear here immediately after publishing.</div></section></main>;
}
